export const MacroMossPage = () => (
    <div className="container pt-8 mx-auto max-w-8xl text-left text-foreground overflow-x-hidden">

        <img src="/assets/projects/macro_moss/card_img_macromoss.png" className="w-full lg:max-h-80 rounded-lg mb-8 object-cover" />

        <span className="text-xs font-light tracking-widest uppercase text-primary/70">Procedural</span>
        <h1 className="text-foreground text-6xl font-bold mt-2 mb-5">Macro Moss</h1>
        <p className="text-foreground/40 text-sm mb-8">Tools:
            <span className="text-foreground/70 border border-primary/30 rounded-md px-2 py-1 ml-2">Houdini</span>
        </p>

        <div className="py-4 pb-8 text-foreground/70 text-sm leading-relaxed max-w-2xl">
            <p>In this project I explored Houdini's workflow and
                worked with VEX scripting. The goal was to create a
                detailed procedural of the Comatricha Nigra, a type of
                slime mold, with valuable guidance from my mentor
                Albert Szostkiewicz during the Women in Animation
                Mentorship.</p>

            <p className="mt-4">Each stem is generated by scattering points across a
                log asset and shaped using polywire. A ramp thickness
                multiplier controls the profile and taper while B-spline
                interpolation defines the curve from tip to trunk. The
                heads are built from a sphere base with ramp-
                controlled size variation and surface noise applied
                through a mountain node. I also implemented a web
                system that uses attribute wrangles to identify anchor
                points.</p>
        </div>
    </div>
);

    